// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKu7T5D83e3L1J5hGT0dY1f5dEw8Dqg-k',
    appId: '1:739988890096:android:e56b6e6549734cb5333d35',
    messagingSenderId: '739988890096',
    projectId: 'imageresizer-86c33',
    storageBucket: 'imageresizer-86c33.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4KB1NVxCPzGtKL7mIR6L5mh7ArSE-Kuo',
    appId: '1:739988890096:web:a782320ee47036cc333d35',
    messagingSenderId: '739988890096',
    projectId: 'imageresizer-86c33',
    authDomain: 'imageresizer-86c33.firebaseapp.com',
    storageBucket: 'imageresizer-86c33.firebasestorage.app',
    measurementId: 'G-2VC94CCP84',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXmDyId1SlsTeuZ3Z0fcehQN-bDNX_7o',
    appId: '1:739988890096:ios:53062eed274b1509333d35',
    messagingSenderId: '739988890096',
    projectId: 'imageresizer-86c33',
    storageBucket: 'imageresizer-86c33.firebasestorage.app',
    iosBundleId: 'com.example.imageResizer',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXmDyId1SlsTeuZ3Z0fcehQN-bDNX_7o',
    appId: '1:739988890096:ios:53062eed274b1509333d35',
    messagingSenderId: '739988890096',
    projectId: 'imageresizer-86c33',
    storageBucket: 'imageresizer-86c33.firebasestorage.app',
    iosBundleId: 'com.example.imageResizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4KB1NVxCPzGtKL7mIR6L5mh7ArSE-Kuo',
    appId: '1:739988890096:web:cd625c8af3ae5361333d35',
    messagingSenderId: '739988890096',
    projectId: 'imageresizer-86c33',
    authDomain: 'imageresizer-86c33.firebaseapp.com',
    storageBucket: 'imageresizer-86c33.firebasestorage.app',
    measurementId: 'G-YM3PTRSV62',
  );
}
