import '../../data/models/image_preset.dart';

class PresetConstants {
  PresetConstants._();

  static const List<ImagePreset> indianGovtPresets = [
    ImagePreset(
      id: 'ssc_photo',
      name: 'SSC Photo',
      description: '20 KB to 50 KB · 3.5cm x 4.5cm (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 450,
      outputFormat: 'jpg',
      badgeText: '20-50 KB',
      iconEmoji: '🧑‍💼',
    ),
    ImagePreset(
      id: 'ssc_signature',
      name: 'SSC Signature',
      description: '10 KB to 20 KB · 4.0cm x 2.0cm (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 19,
      minSizeKB: 10,
      targetWidth: 400,
      targetHeight: 200,
      outputFormat: 'jpg',
      badgeText: '10-20 KB',
      iconEmoji: '✍️',
    ),
    ImagePreset(
      id: 'cg_vyapam_photo',
      name: 'CG Vyapam Photo',
      description: 'Strictly Under 50 KB (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 48,
      targetWidth: 350,
      targetHeight: 450,
      outputFormat: 'jpg',
      badgeText: '< 50 KB',
      iconEmoji: '🎯',
    ),
    ImagePreset(
      id: 'cg_vyapam_sig',
      name: 'CG Vyapam Signature',
      description: 'Strictly Under 20 KB (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 19,
      targetWidth: 400,
      targetHeight: 200,
      outputFormat: 'jpg',
      badgeText: '< 20 KB',
      iconEmoji: '🖋️',
    ),
    ImagePreset(
      id: 'upsc_photo',
      name: 'UPSC Civil Services Photo',
      description: '20 KB to 300 KB · 350x350 px (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 250,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 350,
      outputFormat: 'jpg',
      badgeText: '20-300 KB',
      iconEmoji: '🏛️',
    ),
    ImagePreset(
      id: 'ibps_photo',
      name: 'IBPS / Bank PO Photo',
      description: '20 KB to 50 KB · 200x230 px (JPG)',
      category: PresetCategory.exam,
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 200,
      targetHeight: 230,
      outputFormat: 'jpg',
      badgeText: '20-50 KB',
      iconEmoji: '🏦',
    ),
    ImagePreset(
      id: 'passport_in',
      name: 'Indian Passport Photo',
      description: '3.5cm x 4.5cm · White Background',
      category: PresetCategory.identity,
      targetSizeKB: 100,
      targetWidth: 413,
      targetHeight: 531,
      outputFormat: 'jpg',
      badgeText: '3.5x4.5 cm',
      iconEmoji: '🛂',
    ),
    ImagePreset(
      id: 'pan_card_doc',
      name: 'PAN / Aadhaar Upload',
      description: 'Under 200 KB · High Legibility',
      category: PresetCategory.identity,
      targetSizeKB: 190,
      outputFormat: 'jpg',
      badgeText: '< 200 KB',
      iconEmoji: '🪪',
    ),
  ];
}
