import '../../data/models/image_preset.dart';

class PresetConstants {
  PresetConstants._();

  static const List<ImagePreset> indianGovtPresets = [
    // -------------------------------------------------------------
    // CENTRAL GOVT (SSC, UPSC, Railways)
    // -------------------------------------------------------------
    ImagePreset(
      id: 'ssc_signature',
      name: 'SSC Signature',
      description: '10 KB to 20 KB · 4.0cm x 2.0cm · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.centralGovt,
      searchKeywords: ['ssc', 'signature', 'sign', 'cgl', 'chsl', 'mts', 'gd'],
      targetSizeKB: 19,
      minSizeKB: 10,
      targetWidth: 400,
      targetHeight: 200,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 10-20 KB',
      iconEmoji: '✍️',
    ),
    ImagePreset(
      id: 'upsc_photo',
      name: 'UPSC Civil Services Photo',
      description: '20 KB to 300 KB · 350x350 px · 300 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.centralGovt,
      searchKeywords: [
        'upsc',
        'ias',
        'ips',
        'ifs',
        'civil services',
        'cse',
        'union public service',
        'photo',
      ],
      targetSizeKB: 250,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 350,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 20-300 KB',
      iconEmoji: '🏛️',
    ),
    ImagePreset(
      id: 'upsc_signature',
      name: 'UPSC Signature',
      description: '20 KB to 300 KB · 350x350 px · 300 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.centralGovt,
      searchKeywords: ['upsc', 'signature', 'sign', 'ias', 'ips', 'cse'],
      targetSizeKB: 250,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 350,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 20-300 KB',
      iconEmoji: '🖋️',
    ),
    ImagePreset(
      id: 'rrb_railway_photo',
      name: 'Railway RRB Photo',
      description: '20 KB to 50 KB · 35mm x 45mm · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.centralGovt,
      searchKeywords: [
        'railway',
        'rrb',
        'ntpc',
        'group d',
        'alp',
        'rpf',
        'photo',
      ],
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 20-50 KB',
      iconEmoji: '🚆',
    ),

    // -------------------------------------------------------------
    // STATE PSC (CG Vyapam, BPSC, UPPSC, MPPSC)
    // -------------------------------------------------------------
    ImagePreset(
      id: 'cg_vyapam_photo',
      name: 'CG Vyapam Photo',
      description: 'Strictly Under 50 KB · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.statePsc,
      searchKeywords: [
        'cg vyapam',
        'chhattisgarh',
        'cg psc',
        'patwari',
        'sub inspector',
        'photo',
      ],
      targetSizeKB: 48,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '< 50 KB',
      iconEmoji: '🎯',
    ),
    ImagePreset(
      id: 'cg_vyapam_sig',
      name: 'CG Vyapam Signature',
      description: 'Strictly Under 20 KB · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.statePsc,
      searchKeywords: [
        'cg vyapam',
        'signature',
        'sign',
        'chhattisgarh',
        'vyapam',
      ],
      targetSizeKB: 19,
      targetWidth: 400,
      targetHeight: 200,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '< 20 KB',
      iconEmoji: '🖋️',
    ),
    ImagePreset(
      id: 'bpsc_photo',
      name: 'BPSC / Bihar Teacher Photo',
      description: '25 KB to 100 KB · 200 DPI · Clear BG',
      category: PresetCategory.exam,
      examCategory: ExamCategory.statePsc,
      searchKeywords: ['bpsc', 'bihar', 'tre', 'teacher', 'patna', 'photo'],
      targetSizeKB: 90,
      minSizeKB: 25,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 25-100 KB',
      iconEmoji: '📜',
    ),
    ImagePreset(
      id: 'uppsc_photo',
      name: 'UPPSC / UP Police Photo',
      description: 'Under 50 KB · 3.5cm x 4.5cm · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.statePsc,
      searchKeywords: [
        'uppsc',
        'up police',
        'upsssc',
        'ro aro',
        'lucknow',
        'photo',
      ],
      targetSizeKB: 48,
      minSizeKB: 10,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · < 50 KB',
      iconEmoji: '🗺️',
    ),
    ImagePreset(
      id: 'mppsc_photo',
      name: 'MPPSC / MP Police Photo',
      description: '20 KB to 100 KB · 200 DPI · White BG',
      category: PresetCategory.exam,
      examCategory: ExamCategory.statePsc,
      searchKeywords: [
        'mppsc',
        'mp police',
        'madhya pradesh',
        'esb',
        'peb',
        'photo',
      ],
      targetSizeKB: 90,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 20-100 KB',
      iconEmoji: '🦁',
    ),

    // -------------------------------------------------------------
    // BANKING (IBPS, SBI)
    // -------------------------------------------------------------
    ImagePreset(
      id: 'ibps_photo',
      name: 'IBPS / Bank PO Photo',
      description: '20 KB to 50 KB · 200x230 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.banking,
      searchKeywords: [
        'ibps',
        'bank po',
        'clerk',
        'rrb',
        'so',
        'banking',
        'photo',
      ],
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 200,
      targetHeight: 230,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 20-50 KB',
      iconEmoji: '🏦',
    ),
    ImagePreset(
      id: 'ibps_signature',
      name: 'IBPS Signature',
      description: '10 KB to 20 KB · 140x60 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.banking,
      searchKeywords: ['ibps', 'signature', 'sign', 'banking', 'bank'],
      targetSizeKB: 19,
      minSizeKB: 10,
      targetWidth: 140,
      targetHeight: 60,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 10-20 KB',
      iconEmoji: '✍️',
    ),
    ImagePreset(
      id: 'sbi_photo',
      name: 'SBI PO / Clerk Photo',
      description: '20 KB to 50 KB · 200x230 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.banking,
      searchKeywords: ['sbi', 'state bank', 'po', 'clerk', 'banking', 'photo'],
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 200,
      targetHeight: 230,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 20-50 KB',
      iconEmoji: '🏛️',
    ),
    ImagePreset(
      id: 'sbi_thumb',
      name: 'SBI Left Thumb Impression',
      description: '20 KB to 50 KB · 240x240 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.banking,
      searchKeywords: [
        'sbi',
        'thumb',
        'left thumb',
        'impression',
        'ibps',
        'angutha',
      ],
      targetSizeKB: 48,
      minSizeKB: 20,
      targetWidth: 240,
      targetHeight: 240,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 20-50 KB',
      iconEmoji: '👍',
    ),
    ImagePreset(
      id: 'ibps_declaration',
      name: 'IBPS / SBI Declaration',
      description: '50 KB to 100 KB · 800x400 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.banking,
      searchKeywords: [
        'ibps',
        'sbi',
        'declaration',
        'handwritten',
        'banking',
        'po',
        'clerk',
      ],
      targetSizeKB: 90,
      minSizeKB: 50,
      targetWidth: 800,
      targetHeight: 400,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 50-100 KB',
      iconEmoji: '📝',
    ),

    // -------------------------------------------------------------
    // DEFENCE (NDA, CDS, AFCAT, Agniveer)
    // -------------------------------------------------------------
    ImagePreset(
      id: 'nda_cds_photo',
      name: 'NDA / CDS Defence Photo',
      description: '20 KB to 300 KB · 350x350 px · 300 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.defence,
      searchKeywords: [
        'nda',
        'cds',
        'defence',
        'army',
        'navy',
        'airforce',
        'upsc',
        'photo',
      ],
      targetSizeKB: 250,
      minSizeKB: 20,
      targetWidth: 350,
      targetHeight: 350,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 20-300 KB',
      iconEmoji: '🎖️',
    ),
    ImagePreset(
      id: 'afcat_photo',
      name: 'AFCAT Air Force Photo',
      description: '10 KB to 50 KB · 300 DPI · Frontal View',
      category: PresetCategory.exam,
      examCategory: ExamCategory.defence,
      searchKeywords: [
        'afcat',
        'air force',
        'iaf',
        'flying',
        'ground duty',
        'photo',
      ],
      targetSizeKB: 48,
      minSizeKB: 10,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 10-50 KB',
      iconEmoji: '✈️',
    ),
    ImagePreset(
      id: 'agniveer_photo',
      name: 'Agniveer Army / Navy Photo',
      description: '10 KB to 20 KB · 200 DPI · White BG',
      category: PresetCategory.exam,
      examCategory: ExamCategory.defence,
      searchKeywords: [
        'agniveer',
        'army rally',
        'navy',
        'airforce',
        'join indian army',
        'photo',
      ],
      targetSizeKB: 19,
      minSizeKB: 10,
      targetWidth: 300,
      targetHeight: 400,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 10-20 KB',
      iconEmoji: '🪖',
    ),

    // -------------------------------------------------------------
    // ACADEMIC (GATE, JEE, NEET, CUET)
    // -------------------------------------------------------------
    ImagePreset(
      id: 'gate_photo',
      name: 'GATE 2025/2026 Photo',
      description: '5 KB to 200 KB · 480x640 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'gate',
        'iit',
        'iisc',
        'engineering',
        'mtech',
        'psu',
        'photo',
      ],
      targetSizeKB: 150,
      minSizeKB: 5,
      targetWidth: 480,
      targetHeight: 640,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 5-200 KB',
      iconEmoji: '🎓',
    ),
    ImagePreset(
      id: 'gate_signature',
      name: 'GATE Signature',
      description: '5 KB to 200 KB · 160x560 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: ['gate', 'signature', 'sign', 'iit', 'engineering'],
      targetSizeKB: 150,
      minSizeKB: 5,
      targetWidth: 560,
      targetHeight: 160,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 5-200 KB',
      iconEmoji: '✍️',
    ),
    ImagePreset(
      id: 'jee_main_photo',
      name: 'JEE Main (NTA) Photo',
      description: '10 KB to 200 KB · 300 DPI · 80% Face',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'jee',
        'jee main',
        'jee advanced',
        'iit',
        'nit',
        'nta',
        'photo',
      ],
      targetSizeKB: 180,
      minSizeKB: 10,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 10-200 KB',
      iconEmoji: '📐',
    ),
    ImagePreset(
      id: 'neet_passport_photo',
      name: 'NEET UG Passport Photo',
      description: '10 KB to 200 KB · White BG with Name & Date',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'neet',
        'neet ug',
        'medical',
        'mbbs',
        'nta',
        'doctor',
        'photo',
      ],
      targetSizeKB: 180,
      minSizeKB: 10,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 10-200 KB',
      iconEmoji: '🩺',
    ),
    ImagePreset(
      id: 'neet_postcard_photo',
      name: 'NEET 4x6 Postcard Photo',
      description: '10 KB to 200 KB · 4"x6" Postcard Size',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'neet',
        'postcard',
        'post card',
        '4x6',
        'medical',
        'mbbs',
      ],
      targetSizeKB: 180,
      minSizeKB: 10,
      targetWidth: 600,
      targetHeight: 900,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 4x6 Postcard',
      iconEmoji: '🖼️',
    ),
    ImagePreset(
      id: 'cuet_photo',
      name: 'CUET UG / PG Photo',
      description: '10 KB to 200 KB · 200 DPI · Plain BG',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'cuet',
        'nta',
        'university',
        'college admission',
        'photo',
      ],
      targetSizeKB: 180,
      minSizeKB: 10,
      targetWidth: 350,
      targetHeight: 450,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 10-200 KB',
      iconEmoji: '📚',
    ),
    ImagePreset(
      id: 'nta_signature',
      name: 'JEE / NEET Signature (NTA)',
      description: '4 KB to 30 KB · 350x150 px · 200 DPI',
      category: PresetCategory.exam,
      examCategory: ExamCategory.academic,
      searchKeywords: [
        'jee',
        'neet',
        'cuet',
        'nta',
        'signature',
        'sign',
        'medical',
        'engineering',
      ],
      targetSizeKB: 25,
      minSizeKB: 4,
      targetWidth: 350,
      targetHeight: 150,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · 4-30 KB',
      iconEmoji: '✍️',
    ),

    // -------------------------------------------------------------
    // ID & IDENTITY DOCS
    // -------------------------------------------------------------
    ImagePreset(
      id: 'passport_in',
      name: 'Indian Passport Photo',
      description: '3.5cm x 4.5cm · 300 DPI · White BG',
      category: PresetCategory.identity,
      examCategory: ExamCategory.identity,
      searchKeywords: [
        'passport',
        'seva',
        'visa',
        'embassy',
        'indian passport',
        '35x45',
      ],
      targetSizeKB: 100,
      targetWidth: 413,
      targetHeight: 531,
      targetDpi: 300,
      outputFormat: 'jpg',
      badgeText: '300 DPI · 3.5x4.5 cm',
      iconEmoji: '🛂',
    ),
    ImagePreset(
      id: 'pan_card_doc',
      name: 'PAN / Aadhaar Upload',
      description: 'Under 200 KB · 200 DPI · High Legibility',
      category: PresetCategory.identity,
      examCategory: ExamCategory.identity,
      searchKeywords: [
        'pan',
        'aadhaar',
        'nsdl',
        'uti',
        'uidai',
        'identity card',
        'kyc',
      ],
      targetSizeKB: 190,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · < 200 KB',
      iconEmoji: '🪪',
    ),
    ImagePreset(
      id: 'driving_license_doc',
      name: 'Driving License / Sarathi',
      description: 'Under 200 KB · 200 DPI · Parivahan Upload',
      category: PresetCategory.identity,
      examCategory: ExamCategory.identity,
      searchKeywords: [
        'driving license',
        'dl',
        'parivahan',
        'sarathi',
        'rto',
        'vehicle',
      ],
      targetSizeKB: 190,
      targetDpi: 200,
      outputFormat: 'jpg',
      badgeText: '200 DPI · < 200 KB',
      iconEmoji: '🚗',
    ),
  ];
}
